services:
  - type: web
    name: calendarai-backend
    env: java
    plan: free
    buildCommand: mvn -DskipTests package
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 10000
